apiVersion: 1

datasources:
  - name: Pokedex Database
    type: postgres
    access: proxy
    url: postgres:5432
    user: pkmn
    uid: postgres
    isDefault: true
    editable: false
    jsonData:
      database: pokedex
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: pkmn
